name: C/C++ CI

on: [push]

jobs:
  Ubuntu:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [Debug, Release]
        standard: [14, 17]

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        sudo apt -f install libcurl4-openssl-dev
    - name: Build & Test
      run: |
        cmake -E remove_directory build
        cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_CXX_STANDARD=${{ matrix.standard }} -DCMAKE_CXX_FLAGS="-Werror -fsanitize=address,undefined" -DENABLE_DATE_TESTING=ON -DBUILD_SHARED_LIBS=ON -DCOMPILE_WITH_C_LOCALE=ON
        cmake --build build
        cd build
        ctest --output-on-failure
        
  Windows:

    runs-on: windows-latest
    strategy:
      matrix:
        config: [Release] # For some reason tests hang for Debug builds
        standard: [14, 17]
    
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        vcpkg install curl:x64-windows
    - name: Build & Test
      run: | 
        cmake -E remove_directory build
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake" -DCMAKE_CXX_STANDARD=${{ matrix.standard }} -DENABLE_DATE_TESTING=ON -DBUILD_SHARED_LIBS=ON -DCOMPILE_WITH_C_LOCALE=ON
        cmake --build build --config ${{ matrix.config }}
        cd build
        # Temporary disabled failing test "date_test_pass_durations_output_test" on Windows builds
        ctest --output-on-failure --build-config ${{ matrix.config }} -E "date_test_pass_durations_output_test"

  macOS:

    runs-on: macOS-latest
    strategy:
      matrix:
        config: [Debug, Release]
        standard: [14, 17]

    steps:
    - uses: actions/checkout@v1
    - name: Build & Test
      run: |
        cmake -E remove_directory build
        cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_CXX_STANDARD=${{ matrix.standard }} -DCMAKE_CXX_FLAGS="-Werror -fsanitize=address,undefined" -DENABLE_DATE_TESTING=ON -DBUILD_SHARED_LIBS=ON -DCOMPILE_WITH_C_LOCALE=ON
        cmake --build build
        cd build
        ctest --output-on-failure